**series**

In [13]:
import numpy as np
import pandas as pd

In [14]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [15]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [16]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [17]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [18]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

**dataframes**

In [35]:
import pandas as pd

data = {
    "Name": ["Sharath", "Rahul", "Sneha"],
    "Age": [21, 22, 23],
    "City": ["Udupi", "Bangalore", "Mysore"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age       City
0  Sharath   21      Udupi
1    Rahul   22  Bangalore
2    Sneha   23     Mysore

In [20]:
print(df.head())        # Show first 5 rows
print(df.tail())        # Show last 5 rows
print(df.columns)       # Show column names
print(df["Name"])       # Show 'Name' column
print(df["Age"].mean()) # Average age
print(df[["Name","City"]])

      Name  Age       City
0  Sharath   21      Udupi
1    Rahul   22  Bangalore
2    Sneha   23     Mysore
      Name  Age       City
0  Sharath   21      Udupi
1    Rahul   22  Bangalore
2    Sneha   23     Mysore
Index(['Name', 'Age', 'City'], dtype='object')
0    Sharath
1      Rahul
2      Sneha
Name: Name, dtype: object
22.0
      Name       City
0  Sharath      Udupi
1    Rahul  Bangalore
2    Sneha     Mysore

In [21]:
data_list=[
    ['sharath',28,'udupi',77000],
    ['rahul',32,'mlore',65000],
    ['akash',18,'blore',1500],
    ['bharath',77,'hassan',17000],
]
df2=pd.DataFrame(data_list)
df2

         0   1       2      3
0  sharath  28   udupi  77000
1    rahul  32   mlore  65000
2    akash  18   blore   1500
3  bharath  77  hassan  17000

creating new column

In [36]:
df["role"]=['hr','engi','manager']
df

      Name  Age       City     role
0  Sharath   21      Udupi       hr
1    Rahul   22  Bangalore     engi
2    Sneha   23     Mysore  manager

In [37]:
# Show only rows where age > 21
print(df[df["Age"] > 21])

    Name  Age       City     role
1  Rahul   22  Bangalore     engi
2  Sneha   23     Mysore  manager

In [38]:
df["Passed"] = [True, False, True]
print(df)

      Name  Age       City     role  Passed
0  Sharath   21      Udupi       hr    True
1    Rahul   22  Bangalore     engi   False
2    Sneha   23     Mysore  manager    True

In [25]:
import pandas as pd

data = {
    "Student": ["Anil", "Divya", "Kiran", "Sneha"],
    "Marks": [85, 92, 76, 88],
    "Subject": ["Math", "Science", "History", "Math"]
}

df = pd.DataFrame(data)

# 1. Print top 2 rows
print(df.head(2))

# 2. Print average marks
print("Average:", df["Marks"].mean())

# 3. Show students who scored > 80
print(df[df["Marks"] > 80])

  Student  Marks  Subject
0    Anil     85     Math
1   Divya     92  Science
Average: 85.25
  Student  Marks  Subject
0    Anil     85     Math
1   Divya     92  Science
3   Sneha     88     Math

In [26]:
import os

os.listdir('/kaggle/input')

[]

**delete a column**

**df.drop('role',axis=1,inplace=True)**

df.drop('role',axis=1,inplace=True)
df.drop(['role','Passed'],axis=1,inplace=True)
df.drop(0,axis=0)
importont****

In [39]:
df

      Name  Age       City     role  Passed
0  Sharath   21      Udupi       hr    True
1    Rahul   22  Bangalore     engi   False
2    Sneha   23     Mysore  manager    True

In [40]:
df.loc[[0,1]]

      Name  Age       City  role  Passed
0  Sharath   21      Udupi    hr    True
1    Rahul   22  Bangalore  engi   False

In [29]:
df.iloc[2]

Student      Kiran
Marks           76
Subject    History
Name: 2, dtype: object

**df.loc[[1,2]][['City','Passed']]**

In [41]:
df

      Name  Age       City     role  Passed
0  Sharath   21      Udupi       hr    True
1    Rahul   22  Bangalore     engi   False
2    Sneha   23     Mysore  manager    True

In [43]:
#df[(df["Age"] > 21) & (df["City"] == 'Mysore')]

    Name  Age    City     role  Passed
2  Sneha   23  Mysore  manager    True

**dataframe with CSV**

In [46]:
import pandas as pd

df = pd.read_csv("/kaggle/input/student-csv/student.csv")
print(df)

      Name  Age  Score       City
0  Sharath   21     85      Udupi
1    Rahul   22     78  Bangalore
2    Sneha   23     92     Mysore
3     Anil   20     66      Udupi
4    Divya   22     89    Chennai

In [47]:
print(df.head())        # First 5 rows
print(df.info())        # Data types, non-null info
print(df.describe())    # Stats summary (mean, std, min, max)
print(df.columns)       # Column names

      Name  Age  Score       City
0  Sharath   21     85      Udupi
1    Rahul   22     78  Bangalore
2    Sneha   23     92     Mysore
3     Anil   20     66      Udupi
4    Divya   22     89    Chennai
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Score   5 non-null      int64
 3   City    5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None
             Age      Score
count   5.000000   5.000000
mean   21.600000  82.000000
std     1.140175  10.368221
min    20.000000  66.000000
25%    21.000000  78.000000
50%    22.000000  85.000000
75%    22.000000  89.000000
max    23.000000  92.000000
Index(['Name', 'Age', 'Score', 'City'], dtype='object')

In [48]:
high_scores = df[df["Score"] > 80]
print(high_scores)

      Name  Age  Score     City
0  Sharath   21     85    Udupi
2    Sneha   23     92   Mysore
4    Divya   22     89  Chennai

**missing value**

In [76]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore", category=RuntimeWarning)

data1 = {
    "A": [1,2,3,np.nan,np.nan],
    "B": [25, np.nan, np.nan, 22,np.nan],
    "C": [1, 2, np.nan,4,np.nan],
    "D": [1, 2, 3,4,5]
    
}
df=pd.DataFrame(data1)
df

     A     B    C  D
0  1.0  25.0  1.0  1
1  2.0   NaN  2.0  2
2  3.0   NaN  NaN  3
3  NaN  22.0  4.0  4
4  NaN   NaN  NaN  5

In [73]:
df.isna()

       A      B      C      D
0  False  False   True  False
1  False   True  False  False
2  False   True   True  False
3   True  False  False  False
4   True   True   True  False

In [69]:
df.isna().sum()

A    2
B    3
C    3
D    0
dtype: int64

In [70]:
df.isna().any()

A     True
B     True
C     True
D    False
dtype: bool

In [78]:
df.dropna()

     A     B    C  D
0  1.0  25.0  1.0  1

In [77]:
df

     A     B    C  D
0  1.0  25.0  1.0  1
1  2.0   NaN  2.0  2
2  3.0   NaN  NaN  3
3  NaN  22.0  4.0  4
4  NaN   NaN  NaN  5