**series**

In [1]:
import numpy as np
import pandas as pd

In [2]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [5]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [6]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

**dataframes**

In [7]:
import pandas as pd

data = {
    "Name": ["Sharath", "Rahul", "Sneha"],
    "Age": [21, 22, 23],
    "City": ["Udupi", "Bangalore", "Mysore"]
}

df = pd.DataFrame(data)
print(df)

      Name  Age       City
0  Sharath   21      Udupi
1    Rahul   22  Bangalore
2    Sneha   23     Mysore

In [8]:
print(df.head())        # Show first 5 rows
print(df.tail())        # Show last 5 rows
print(df.columns)       # Show column names
print(df["Name"])       # Show 'Name' column
print(df["Age"].mean()) # Average age
print(df[["Name","City"]])

      Name  Age       City
0  Sharath   21      Udupi
1    Rahul   22  Bangalore
2    Sneha   23     Mysore
      Name  Age       City
0  Sharath   21      Udupi
1    Rahul   22  Bangalore
2    Sneha   23     Mysore
Index(['Name', 'Age', 'City'], dtype='object')
0    Sharath
1      Rahul
2      Sneha
Name: Name, dtype: object
22.0
      Name       City
0  Sharath      Udupi
1    Rahul  Bangalore
2    Sneha     Mysore

In [9]:
data_list=[
    ['sharath',28,'udupi',77000],
    ['rahul',32,'mlore',65000],
    ['akash',18,'blore',1500],
    ['bharath',77,'hassan',17000],
]
df2=pd.DataFrame(data_list)
df2

         0   1       2      3
0  sharath  28   udupi  77000
1    rahul  32   mlore  65000
2    akash  18   blore   1500
3  bharath  77  hassan  17000

creating new column

In [10]:
df["role"]=['hr','engi','manager']
df

      Name  Age       City     role
0  Sharath   21      Udupi       hr
1    Rahul   22  Bangalore     engi
2    Sneha   23     Mysore  manager

In [11]:
# Show only rows where age > 21
print(df[df["Age"] > 21])

    Name  Age       City     role
1  Rahul   22  Bangalore     engi
2  Sneha   23     Mysore  manager

In [12]:
df["Passed"] = [True, False, True]
print(df)

      Name  Age       City     role  Passed
0  Sharath   21      Udupi       hr    True
1    Rahul   22  Bangalore     engi   False
2    Sneha   23     Mysore  manager    True

In [13]:
import pandas as pd

data = {
    "Student": ["Anil", "Divya", "Kiran", "Sneha"],
    "Marks": [85, 92, 76, 88],
    "Subject": ["Math", "Science", "History", "Math"]
}

df = pd.DataFrame(data)

# 1. Print top 2 rows
print(df.head(2))

# 2. Print average marks
print("Average:", df["Marks"].mean())

# 3. Show students who scored > 80
print(df[df["Marks"] > 80])

  Student  Marks  Subject
0    Anil     85     Math
1   Divya     92  Science
Average: 85.25
  Student  Marks  Subject
0    Anil     85     Math
1   Divya     92  Science
3   Sneha     88     Math

In [14]:
import os

os.listdir('/kaggle/input')

[]

**delete a column**

**df.drop('role',axis=1,inplace=True)**

df.drop('role',axis=1,inplace=True)
df.drop(['role','Passed'],axis=1,inplace=True)
df.drop(0,axis=0)
importont****

In [15]:
df

  Student  Marks  Subject
0    Anil     85     Math
1   Divya     92  Science
2   Kiran     76  History
3   Sneha     88     Math

In [16]:
df.loc[[0,1]]

  Student  Marks  Subject
0    Anil     85     Math
1   Divya     92  Science

In [17]:
df.iloc[2]

Student      Kiran
Marks           76
Subject    History
Name: 2, dtype: object

**df.loc[[1,2]][['City','Passed']]**

In [18]:
df

  Student  Marks  Subject
0    Anil     85     Math
1   Divya     92  Science
2   Kiran     76  History
3   Sneha     88     Math

In [19]:
#df[(df["Age"] > 21) & (df["City"] == 'Mysore')]