Name:sharath shetty
roll no:240970108

# 1. Create Python program to find the average of 10 numbers using while loop

In [6]:
count = 0
total = 0

print("Enter 10 numbers to calculate their average:")

while count < 10:
        number = float(input(f"Enter number {count + 1}: "))
        total += number
        count += 1
        
average = total / 10

print(f"The average of the 10 numbers is: {average}")

Enter 10 numbers to calculate their average:
Enter number 1: 1
Enter number 2: 2
Enter number 3: 3
Enter number 4: 4
Enter number 5: 5
Enter number 6: 6
Enter number 7: 7
Enter number 8: 8
Enter number 9: 9
Enter number 10: 1
The average of the 10 numbers is: 4.6

# output :

Enter 10 numbers to calculate their average:
Enter number 1: 1
Enter number 2: 2
Enter number 3: 3
Enter number 4: 4
Enter number 5: 5
Enter number 6: 6
Enter number 7: 7
Enter number 8: 8
Enter number 9: 9
Enter number 10: 10
The average of the 10 numbers is: 5.5

# 2. Create Python program to find the geometric mean of n numbers

In [14]:
def geometric_mean(numbers):
    product = 1
    n = len(numbers)
    
    for num in numbers:
        product *= num
    
    return product ** (1 / n)

n = int(input("Enter the number of elements: "))
numbers = []

for i in range(n):
        value = float(input(f"Enter number {i+1}: "))
        numbers.append(value)

result = geometric_mean(numbers)
print(f"The geometric mean is: {result}")

Enter the number of elements: 4
Enter number 1: 2
Enter number 2: 3
Enter number 3: 2
Enter number 4: 2
The geometric mean is: 2.213363839400643

# output :
Enter the number of elements: 4
Enter number 1: 2
Enter number 2: 3
Enter number 3: 2
Enter number 4: 2
The geometric mean is: 2.213363839400643

# 3. Create Python program to check whether the given integer is a prime number or not

In [24]:
num = int(input("Enter an integer: "))
flag = False

if num == 0 or num == 1:
    print(num, "is not a prime number")
    
elif num > 1:
    for i in range(2, num):
        if (num % i) == 0:
            flag = True
            break
    if flag:
        print(num, "is not a prime number")
    else:
        print(num, "is a prime number")

Enter an integer: 6
6 is not a prime number

# output :
Enter an integer: 19
19 is a prime number

Enter an integer: 6
6 is not a prime number

# 4. Create Python program to implement linear search and implement binary search

In [44]:
def linear_search(arr, target):
    for index in range(len(arr)):
        if arr[index] == target:
            return index
    return -1


def binary_search(arr, target):
    arr.sort()
    low = 0
    high = len(arr) - 1

    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == target:
            return mid 
        elif arr[mid] < target:
            low = mid + 1 
        else:
            high = mid - 1  

    return -1

In [45]:

n = int(input("Enter the size of the array: "))
array = []
for i in range(n):
    element = int(input(f"Enter element {i + 1}: "))
    array.append(element)
print("Your array:", array)

target= int(input("Enter an target number: "))

linear_result = linear_search(array, target)
binary_result = binary_search(array, target)

if linear_result != -1:
    print(f"Linear Search: Element found at index {linear_result}")
    print(f"Binary Search: Element found at index {binary_result}")
else:
    print("Element not found in the array")

Enter the size of the array: 4
Enter element 1: 2
Enter element 2: 425
Enter element 3: 7
Enter element 4: 8
Your array: [2, 425, 7, 8]
Enter an target number: 8
Linear Search: Element found at index 3
Binary Search: Element found at index 2

# output
Enter the size of the array: 5
Enter element 1: 20
Enter element 2: 30
Enter element 3: 45
Enter element 4: 102
Enter element 5: 39
Your array: [20, 30, 45, 102, 39]
Enter an target number: 45
Linear Search: Element found at index 2
Binary Search: Element found at index 3
    
    
Enter the size of the array: 3
Enter element 1: 6
Enter element 2: 5
Enter element 3: 700
Your array: [6, 5, 700]
Enter an target number: 456
Element not found in the array

# 5. Using math package, Create Python program to find the area of a triangle whose sides

In [43]:
import math

def triangle_area(a, b, c):
    s = (a + b + c) / 2
    area = math.sqrt(s * (s - a) * (s - b) * (s - c))
    return area

a = float(input("Enter side a: "))
b = float(input("Enter side b: "))
c = float(input("Enter side c: "))


if a + b > c and a + c > b and b + c > a:
    result = triangle_area(a, b, c)
    print(f"Area of the triangle is: {result}")
else:
    print("Invalid triangle: the sum of any two sides must be greater than the third side.")

Enter side a: 6
Enter side b: 7
Enter side c: 4
Area of the triangle is: 11.976539567003485

# output
Enter side a: 6
Enter side b: 7
Enter side c: 4
Area of the triangle is: 11.976539567003485

Enter side a: 1
Enter side b: 1
Enter side c: 5
Invalid triangle: the sum of any two sides must be greater than the third side

# Introduction to Pandas

# 1. Create a data frame with details of 10 students

In [16]:
import pandas as pd

data = {
    'Roll Number': [1,2,3,4,5,6,7,8,9,10],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Helen', 'Ian', 'Jane'],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F'],
    'Marks1': [55, 67, 45, 70, 30, 90, 80, 45, 38, 60],
    'Marks2': [65, 34, 50, 80, 25, 95, 85, 40, 55, 70],
    'Marks3': [75, 44, 60, 90, 35, 85, 90, 50, 60, 80]
}

df = pd.DataFrame(data)
df

   Roll Number     Name Gender  Marks1  Marks2  Marks3
0            1    Alice      F      55      65      75
1            2      Bob      M      67      34      44
2            3  Charlie      M      45      50      60
3            4    David      M      70      80      90
4            5      Eva      F      30      25      35
5            6    Frank      M      90      95      85
6            7    Grace      F      80      85      90
7            8    Helen      F      45      40      50
8            9      Ian      M      38      55      60
9           10     Jane      F      60      70      80

# 2. Create a new column with total marks

In [17]:
df['Total Marks'] = df['Marks1'] + df['Marks2'] + df['Marks3']
df

   Roll Number     Name Gender  Marks1  Marks2  Marks3  Total Marks
0            1    Alice      F      55      65      75          195
1            2      Bob      M      67      34      44          145
2            3  Charlie      M      45      50      60          155
3            4    David      M      70      80      90          240
4            5      Eva      F      30      25      35           90
5            6    Frank      M      90      95      85          270
6            7    Grace      F      80      85      90          255
7            8    Helen      F      45      40      50          135
8            9      Ian      M      38      55      60          153
9           10     Jane      F      60      70      80          210

# 3. Find the lowest marks in Marks1

In [11]:
lowest_marks1 = df['Marks1'].min()
print("\nLowest marks in Marks1:", lowest_marks1)

Lowest marks in Marks1: 30

# 4. Find the Highest marks in Marks2

In [12]:
highest_marks2 = df['Marks2'].max()
print("Highest marks in Marks2:", highest_marks2)

Highest marks in Marks2: 95

# 5. Find the average marks in Marks3

In [13]:
average_marks3 = df['Marks3'].mean()
print("Average marks in Marks3:", average_marks3)

Average marks in Marks3: 66.9

# 6. Find student name with highest average

In [14]:
df['Average Marks'] = df[['Marks1', 'Marks2', 'Marks3']].mean(axis=1)
highest_avg_student = df.loc[df['Average Marks'].idxmax(), 'Name']
print("Student with highest average marks:", highest_avg_student)

Student with highest average marks: Frank

# 7. Find how many students failed in Marks2 (<40)

In [15]:
failed_in_marks2 = df[df['Marks2'] < 40].shape[0]
print("Number of students failed in Marks2:", failed_in_marks2)

Number of students failed in Marks2: 2